app = "cyeam-api"
primary_region = "nrt"

[env]
  OTEL_EXPORTER_OTLP_ENDPOINT = "https://otlp.nr-data.net"
  OTEL_EXPORTER_OTLP_PROTOCOL = "http/protobuf"
  OTEL_DEPLOYMENT_ENVIRONMENT = "production"
  OTEL_SERVICE_NAME = "cyeam-api"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
